import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'donghua_detail.dart';

class TopDonghua extends StatelessWidget {
  const TopDonghua({super.key});

  @override
  
  Widget build(BuildContext context) {
    final List<Map<String, dynamic>> donghuaList1 = [
    {'title': 'A Record  of a Mortal is Journey to Immortality',
      'mandarin': '凡人修仙传, Fanren Xiu Xian Chuan: Fanren Feng Qi Tian Nan',
      'rating': 9.60,
      'image': 'assets/DONGHUA/HanLi.jpg',
      'genre': ['Action', 'Adventure', 'Fantasy'],
      'status': 'Completed',
      'studio': 'Original Force, Wonder Cat Animation',
      'releaseDate': '26 July 2020',
      'update': '5 July 2023',
      'duration': '20 min.',
      'totaleps': '17 Episodes',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
        {'titleeps': 'Episode 11', 'url': 'link'},
        {'titleeps': 'Episode 12', 'url': 'link'},
        {'titleeps': 'Episode 13', 'url': 'link'},
        {'titleeps': 'Episode 14', 'url': 'link'},
        {'titleeps': 'Episode 15', 'url': 'link'},
        {'titleeps': 'Episode 16', 'url': 'link'},
        {'titleeps': 'Episode 17', 'url': 'link'},
      ],
      'jenis': 'Donghua',
      'musim': '2020',
      'description': 'Donghua ini bercerita tentang bocah biasa Han Li terlahir dalam kemiskinan. Agar keluarganya dapat hidup lebih baik, ia secara sukarela pergi ke Qixuanmen untuk berpartisipasi dalam ujian masuk, dan akhirnya diterima oleh Dokter Mo. Pada awalnya, Dokter Mo dengan hati-hati mengembangkan dan mengajarkan Han Li keahlian medisnya, yang membuat Han Li sangat berterima kasih kepadanya, tetapi ketika muridnya Zhang Tie menghilang, Han Li menemukan wajah asli Dokter Mo. Dokter Mo mencoba untuk merebut Han Li, tetapi akhirnya dibunuh oleh Han Li. Melalui catatan bunuh diri Dokter Mo, Han Li belajar tentang dunia yang sama sekali baru: keberadaan dunia keabadian. Setelah membantu Qixuanmen untuk melawan musuh asing, Han Li meninggalkan Qixuanmen dan pergi ke rumah Dr. Mo untuk menemukan Nuanyang Baoyu untuk mendetoksifikasi dan membantu keluarga Mo mengalahkan musuh. Mengetahui alamat Tainan Xiaohui melalui mulut putri Dr. Mo, Mo Caihuan, Han Li memutuskan untuk pergi ke Tainan Xiaohui untuk mengikuti jejak para Kultivator. Setelah mengucapkan selamat tinggal kepada keluarganya, …'
    },
    {'title': 'Soul Land Season 2 (Live Action)',
      'mandarin': 'Soul Land 2 (Life Action)',
      'rating': 9.20,
      'image': 'assets/DONGHUA/soul_land2_life.jpg',
      'genre': ['Fantasy', 'Romance'],
      'status': 'Ongoing',
      'studio': 'Tencent Penguin Pictures',
      'releaseDate': '26 November 2024',
      'update': '1 December 2024',
      'duration': '45 min.',
      'totaleps': 'Unknown',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
      ],
      'jenis': 'Donghua Film',
      'musim': '2024',
      'description': 'Final dari Kompetisi Elit Akademi Master Jiwa Benua Tingkat Tinggi telah berakhir. Tang San mengucapkan selamat tinggal dengan rasa berat hati kepada teman-temannya, berjanji untuk bertemu kembali dalam lima tahun, sebelum masing-masing menjalani jalan mereka sendiri. Tang San kemudian pergi bersama ayahnya, Tang Hao, ke sebuah lembah terpencil untuk pelatihan khusus guna meningkatkan kemampuannya. Dengan bantuan Tang Hao, Tang San menjadi lebih tenang melalui pengalaman dan mampu menghadapi tantangan dengan percaya diri. Dai Mu Bai dan Zhu Zhu Qing menerima pengakuan dari keluarga mereka, menjadi Putra Mahkota dan Putri Mahkota Bangsawan dari Kekaisaran Xing Luo. Oscar dan Ning Rong Rong memulai pelatihan yang ketat untuk meningkatkan kekuatan mereka, sementara Ma Hong Jun memulai perjalanan untuk memperluas wawasan mereka.'
    },
    {'title': 'Swallowed Star Season 4',
      'mandarin': 'Tunshi Xingkong 4th Season',
      'rating': 9.20,
      'image': 'assets/DONGHUA/swallowed_star.jpg',
      'genre': ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
      'status': 'Ongoing',
      'studio': 'Sparkly Key Animation Studio',
      'releaseDate': '3 October 2023',
      'update': '3 December 2024',
      'duration': '20 min.',
      'totaleps': '148 Episodes',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
        {'titleeps': 'Episode 11', 'url': 'link'},
        {'titleeps': 'Episode 12', 'url': 'link'},
        {'titleeps': 'Episode 13', 'url': 'link'},
        {'titleeps': 'Episode 14', 'url': 'link'},
        {'titleeps': 'Episode 15', 'url': 'link'},
        {'titleeps': 'Episode 16', 'url': 'link'},
        {'titleeps': 'Episode 17', 'url': 'link'},
        {'titleeps': 'Episode 18', 'url': 'link'},
        {'titleeps': 'Episode 19', 'url': 'link'},
        {'titleeps': 'Episode 20', 'url': 'link'},
        {'titleeps': 'Episode 21', 'url': 'link'},
        {'titleeps': 'Episode 22', 'url': 'link'},
        {'titleeps': 'Episode 23', 'url': 'link'},
        {'titleeps': 'Episode 24', 'url': 'link'},
        {'titleeps': 'Episode 25', 'url': 'link'},
        {'titleeps': 'Episode 26', 'url': 'link'},
        {'titleeps': 'Episode 27', 'url': 'link'},
        {'titleeps': 'Episode 28', 'url': 'link'},
        {'titleeps': 'Episode 29', 'url': 'link'},
        {'titleeps': 'Episode 30', 'url': 'link'},
        {'titleeps': 'Episode 31', 'url': 'link'},
        {'titleeps': 'Episode 32', 'url': 'link'},
        {'titleeps': 'Episode 33', 'url': 'link'},
        {'titleeps': 'Episode 34', 'url': 'link'},
        {'titleeps': 'Episode 35', 'url': 'link'},
        {'titleeps': 'Episode 36', 'url': 'link'},
        {'titleeps': 'Episode 37', 'url': 'link'},
        {'titleeps': 'Episode 38', 'url': 'link'},
        {'titleeps': 'Episode 39', 'url': 'link'},
        {'titleeps': 'Episode 40', 'url': 'link'},
        {'titleeps': 'Episode 41', 'url': 'link'},
        {'titleeps': 'Episode 42', 'url': 'link'},
        {'titleeps': 'Episode 44', 'url': 'link'},
        {'titleeps': 'Episode 45', 'url': 'link'},
        {'titleeps': 'Episode 46', 'url': 'link'},
        {'titleeps': 'Episode 47', 'url': 'link'},
        {'titleeps': 'Episode 48', 'url': 'link'},
        {'titleeps': 'Episode 49', 'url': 'link'},
        {'titleeps': 'Episode 50', 'url': 'link'},
        {'titleeps': 'Episode 51', 'url': 'link'},
        {'titleeps': 'Episode 52', 'url': 'link'},
        {'titleeps': 'Episode 53', 'url': 'link'},
        {'titleeps': 'Episode 54', 'url': 'link'},
        {'titleeps': 'Episode 55', 'url': 'link'},
        {'titleeps': 'Episode 56', 'url': 'link'},
        {'titleeps': 'Episode 57', 'url': 'link'},
        {'titleeps': 'Episode 58', 'url': 'link'},
        {'titleeps': 'Episode 59', 'url': 'link'},
        {'titleeps': 'Episode 60', 'url': 'link'},
        {'titleeps': 'Episode 61', 'url': 'link'},
        {'titleeps': 'Episode 62', 'url': 'link'},
        {'titleeps': 'Episode 63', 'url': 'link'},
        {'titleeps': 'Episode 64', 'url': 'link'},
        {'titleeps': 'Episode 65', 'url': 'link'},
        {'titleeps': 'Episode 66', 'url': 'link'},
        {'titleeps': 'Episode 67', 'url': 'link'},
        {'titleeps': 'Episode 68', 'url': 'link'},
        {'titleeps': 'Episode 69', 'url': 'link'},
        {'titleeps': 'Episode 70', 'url': 'link'},
        {'titleeps': 'Episode 71', 'url': 'link'},
        {'titleeps': 'Episode 72', 'url': 'link'},
        {'titleeps': 'Episode 73', 'url': 'link'},
        {'titleeps': 'Episode 74', 'url': 'link'},
        {'titleeps': 'Episode 75', 'url': 'link'},
        {'titleeps': 'Episode 76', 'url': 'link'},
        {'titleeps': 'Episode 77', 'url': 'link'},
        {'titleeps': 'Episode 78', 'url': 'link'},
        {'titleeps': 'Episode 79', 'url': 'link'},
        {'titleeps': 'Episode 80', 'url': 'link'},
        {'titleeps': 'Episode 81', 'url': 'link'},
        {'titleeps': 'Episode 82', 'url': 'link'},
        {'titleeps': 'Episode 83', 'url': 'link'},
        {'titleeps': 'Episode 84', 'url': 'link'},
        {'titleeps': 'Episode 85', 'url': 'link'},
        {'titleeps': 'Episode 86', 'url': 'link'},
        {'titleeps': 'Episode 87', 'url': 'link'},
        {'titleeps': 'Episode 88', 'url': 'link'},
        {'titleeps': 'Episode 89', 'url': 'link'},
        {'titleeps': 'Episode 90', 'url': 'link'},
        {'titleeps': 'Episode 91', 'url': 'link'},
        {'titleeps': 'Episode 92', 'url': 'link'},
        {'titleeps': 'Episode 93', 'url': 'link'},
        {'titleeps': 'Episode 94', 'url': 'link'},
        {'titleeps': 'Episode 95', 'url': 'link'},
        {'titleeps': 'Episode 96', 'url': 'link'},
        {'titleeps': 'Episode 97', 'url': 'link'},
        {'titleeps': 'Episode 98', 'url': 'link'},
        {'titleeps': 'Episode 99', 'url': 'link'},
        {'titleeps': 'Episode 100', 'url': 'link'},
        {'titleeps': 'Episode 101', 'url': 'link'},
        {'titleeps': 'Episode 102', 'url': 'link'},
        {'titleeps': 'Episode 103', 'url': 'link'},
        {'titleeps': 'Episode 104', 'url': 'link'},
        {'titleeps': 'Episode 105', 'url': 'link'},
        {'titleeps': 'Episode 106', 'url': 'link'},
        {'titleeps': 'Episode 107', 'url': 'link'},
        {'titleeps': 'Episode 108', 'url': 'link'},
        {'titleeps': 'Episode 109', 'url': 'link'},
        {'titleeps': 'Episode 110', 'url': 'link'},
        {'titleeps': 'Episode 111', 'url': 'link'},
        {'titleeps': 'Episode 112', 'url': 'link'},
        {'titleeps': 'Episode 113', 'url': 'link'},
        {'titleeps': 'Episode 114', 'url': 'link'},
        {'titleeps': 'Episode 115', 'url': 'link'},
        {'titleeps': 'Episode 116', 'url': 'link'},
        {'titleeps': 'Episode 117', 'url': 'link'},
        {'titleeps': 'Episode 118', 'url': 'link'},
        {'titleeps': 'Episode 119', 'url': 'link'},
        {'titleeps': 'Episode 120', 'url': 'link'},
        {'titleeps': 'Episode 121', 'url': 'link'},
        {'titleeps': 'Episode 122', 'url': 'link'},
        {'titleeps': 'Episode 123', 'url': 'link'},
        {'titleeps': 'Episode 124', 'url': 'link'},
        {'titleeps': 'Episode 125', 'url': 'link'},
        {'titleeps': 'Episode 126', 'url': 'link'},
        {'titleeps': 'Episode 127', 'url': 'link'},
        {'titleeps': 'Episode 128', 'url': 'link'},
        {'titleeps': 'Episode 129', 'url': 'link'},
        {'titleeps': 'Episode 130', 'url': 'link'},
        {'titleeps': 'Episode 131', 'url': 'link'},
        {'titleeps': 'Episode 132', 'url': 'link'},
        {'titleeps': 'Episode 133', 'url': 'link'},
        {'titleeps': 'Episode 134', 'url': 'link'},
        {'titleeps': 'Episode 135', 'url': 'link'},
        {'titleeps': 'Episode 136', 'url': 'link'},
        {'titleeps': 'Episode 137', 'url': 'link'},
        {'titleeps': 'Episode 138', 'url': 'link'},
        {'titleeps': 'Episode 139', 'url': 'link'},
        {'titleeps': 'Episode 140', 'url': 'link'},
        {'titleeps': 'Episode 141', 'url': 'link'},
        {'titleeps': 'Episode 142', 'url': 'link'},
        {'titleeps': 'Episode 143', 'url': 'link'},
        {'titleeps': 'Episode 144', 'url': 'link'},
        {'titleeps': 'Episode 145', 'url': 'link'},
        {'titleeps': 'Episode 146', 'url': 'link'},
        {'titleeps': 'Episode 147', 'url': 'link'},
        {'titleeps': 'Episode 148', 'url': 'link'},
      ],
      'jenis': 'Donghua',
      'musim': '2023',
      'description': 'Kisah Swallowed Star menghadirkan petualangan yang seru, penuh aksi, dan juga penuh dengan misteri dan rahasia. Dalam setiap langkahnya, Luo Feng selalu dihadapkan pada pilihan-pilihan sulit, yang memaksa dia untuk berpikir secara strategis dan mengevaluasi nilai-nilai dan prinsip-prinsipnya sebagai seorang prajurit. Dengan begitu, cerita Swallowed Star tidak hanya menarik untuk diikuti, tetapi juga memiliki nilai-nilai moral yang mendalam.'
    },
    {'title': 'The Westward 5th Season',
      'mandarin': '西行纪 第五季, 西行纪 年番, Xi Xing Ji: Nian Fan',
      'rating': 9.20,
      'image': 'assets/DONGHUA/xi_xing_ji.jpg',
      'genre': ['Action', 'Adventure', 'Fantasy'],
      'status': 'Ongoing',
      'studio': 'BYMENT',
      'releaseDate': '3 Augustus 2023',
      'update': '6 December 2024',
      'duration': '15 min.',
      'totaleps': '52 Episodes',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
        {'titleeps': 'Episode 11', 'url': 'link'},
        {'titleeps': 'Episode 12', 'url': 'link'},
        {'titleeps': 'Episode 13', 'url': 'link'},
        {'titleeps': 'Episode 14', 'url': 'link'},
        {'titleeps': 'Episode 15', 'url': 'link'},
        {'titleeps': 'Episode 16', 'url': 'link'},
        {'titleeps': 'Episode 17', 'url': 'link'},
        {'titleeps': 'Episode 18', 'url': 'link'},
        {'titleeps': 'Episode 19', 'url': 'link'},
        {'titleeps': 'Episode 20', 'url': 'link'},
        {'titleeps': 'Episode 21', 'url': 'link'},
        {'titleeps': 'Episode 22', 'url': 'link'},
        {'titleeps': 'Episode 23', 'url': 'link'},
        {'titleeps': 'Episode 24', 'url': 'link'},
        {'titleeps': 'Episode 25', 'url': 'link'},
        {'titleeps': 'Episode 26', 'url': 'link'},
        {'titleeps': 'Episode 27', 'url': 'link'},
        {'titleeps': 'Episode 28', 'url': 'link'},
        {'titleeps': 'Episode 29', 'url': 'link'},
        {'titleeps': 'Episode 30', 'url': 'link'},
        {'titleeps': 'Episode 31', 'url': 'link'},
        {'titleeps': 'Episode 32', 'url': 'link'},
        {'titleeps': 'Episode 33', 'url': 'link'},
        {'titleeps': 'Episode 34', 'url': 'link'},
        {'titleeps': 'Episode 35', 'url': 'link'},
        {'titleeps': 'Episode 36', 'url': 'link'},
        {'titleeps': 'Episode 37', 'url': 'link'},
        {'titleeps': 'Episode 38', 'url': 'link'},
        {'titleeps': 'Episode 39', 'url': 'link'},
        {'titleeps': 'Episode 40', 'url': 'link'},
        {'titleeps': 'Episode 41', 'url': 'link'},
        {'titleeps': 'Episode 42', 'url': 'link'},
        {'titleeps': 'Episode 43', 'url': 'link'},
        {'titleeps': 'Episode 44', 'url': 'link'},
        {'titleeps': 'Episode 45', 'url': 'link'},
        {'titleeps': 'Episode 46', 'url': 'link'},
        {'titleeps': 'Episode 47', 'url': 'link'},
        {'titleeps': 'Episode 48', 'url': 'link'},
        {'titleeps': 'Episode 49', 'url': 'link'},
        {'titleeps': 'Episode 50', 'url': 'link'},
        {'titleeps': 'Episode 51', 'url': 'link'},
        {'titleeps': 'Episode 52', 'url': 'link'},
      ],
      'jenis': 'Donghua',
      'musim': '2023',
      'description': '西行纪 第五季, 西行纪 年番, Xi Xing Ji 5th Season.Dari awal perilisan Xi Xing Ji, telah ada peristiwa perjalanan ke Barat adalah konspirasi surga. Setelah Kitab Suci hilang selama lebih dari satu dekade Surga mengirim pasukannya untuk mencari Kitab Suci agar tidak sekali lagi jatuh ke tangan surga. Di season 4, kisahnya dipaparkan ketika para dewa yang tidak takut mati membuat mereka datang. Wukong akan kembali tanpa takut pada para Dewa dan Buddha di Langit! Para dewa dan monster bertarung di garis depan dan jiwa Wukong muncul kembali.'
    },
    {'title': 'Perfect World',
      'mandarin': '完美世界, Wanmei Shijie',
      'rating': 8.00,
      'image': 'assets/DONGHUA/perfect_world.jpg',
      'genre': ['Action', 'Adventure', 'Fantasy'],
      'status': 'Ongoing',
      'studio': 'Shanghai Foch Film Culture Investment',
      'releaseDate': '24 April 2021',
      'update': '6 December 2024',
      'duration': '20 min.',
      'titleeps': '120 Episodes',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
        {'titleeps': 'Episode 11', 'url': 'link'},
        {'titleeps': 'Episode 12', 'url': 'link'},
        {'titleeps': 'Episode 13', 'url': 'link'},
        {'titleeps': 'Episode 14', 'url': 'link'},
        {'titleeps': 'Episode 15', 'url': 'link'},
        {'titleeps': 'Episode 16', 'url': 'link'},
        {'titleeps': 'Episode 17', 'url': 'link'},
        {'titleeps': 'Episode 18', 'url': 'link'},
        {'titleeps': 'Episode 19', 'url': 'link'},
        {'titleeps': 'Episode 20', 'url': 'link'},
        {'titleeps': 'Episode 21', 'url': 'link'},
        {'titleeps': 'Episode 22', 'url': 'link'},
        {'titleeps': 'Episode 23', 'url': 'link'},
        {'titleeps': 'Episode 24', 'url': 'link'},
        {'titleeps': 'Episode 25', 'url': 'link'},
        {'titleeps': 'Episode 26', 'url': 'link'},
        {'titleeps': 'Episode 27', 'url': 'link'},
        {'titleeps': 'Episode 28', 'url': 'link'},
        {'titleeps': 'Episode 29', 'url': 'link'},
        {'titleeps': 'Episode 30', 'url': 'link'},
        {'titleeps': 'Episode 31', 'url': 'link'},
        {'titleeps': 'Episode 32', 'url': 'link'},
        {'titleeps': 'Episode 33', 'url': 'link'},
        {'titleeps': 'Episode 34', 'url': 'link'},
        {'titleeps': 'Episode 35', 'url': 'link'},
        {'titleeps': 'Episode 36', 'url': 'link'},
        {'titleeps': 'Episode 37', 'url': 'link'},
        {'titleeps': 'Episode 38', 'url': 'link'},
        {'titleeps': 'Episode 39', 'url': 'link'},
        {'titleeps': 'Episode 40', 'url': 'link'},
        {'titleeps': 'Episode 41', 'url': 'link'},
        {'titleeps': 'Episode 42', 'url': 'link'},
        {'titleeps': 'Episode 44', 'url': 'link'},
        {'titleeps': 'Episode 45', 'url': 'link'},
        {'titleeps': 'Episode 46', 'url': 'link'},
        {'titleeps': 'Episode 47', 'url': 'link'},
        {'titleeps': 'Episode 48', 'url': 'link'},
        {'titleeps': 'Episode 49', 'url': 'link'},
        {'titleeps': 'Episode 50', 'url': 'link'},
        {'titleeps': 'Episode 51', 'url': 'link'},
        {'titleeps': 'Episode 52', 'url': 'link'},
        {'titleeps': 'Episode 53', 'url': 'link'},
        {'titleeps': 'Episode 54', 'url': 'link'},
        {'titleeps': 'Episode 55', 'url': 'link'},
        {'titleeps': 'Episode 56', 'url': 'link'},
        {'titleeps': 'Episode 57', 'url': 'link'},
        {'titleeps': 'Episode 58', 'url': 'link'},
        {'titleeps': 'Episode 59', 'url': 'link'},
        {'titleeps': 'Episode 60', 'url': 'link'},
        {'titleeps': 'Episode 61', 'url': 'link'},
        {'titleeps': 'Episode 62', 'url': 'link'},
        {'titleeps': 'Episode 63', 'url': 'link'},
        {'titleeps': 'Episode 64', 'url': 'link'},
        {'titleeps': 'Episode 65', 'url': 'link'},
        {'titleeps': 'Episode 66', 'url': 'link'},
        {'titleeps': 'Episode 67', 'url': 'link'},
        {'titleeps': 'Episode 68', 'url': 'link'},
        {'titleeps': 'Episode 69', 'url': 'link'},
        {'titleeps': 'Episode 70', 'url': 'link'},
        {'titleeps': 'Episode 71', 'url': 'link'},
        {'titleeps': 'Episode 72', 'url': 'link'},
        {'titleeps': 'Episode 73', 'url': 'link'},
        {'titleeps': 'Episode 74', 'url': 'link'},
        {'titleeps': 'Episode 75', 'url': 'link'},
        {'titleeps': 'Episode 76', 'url': 'link'},
        {'titleeps': 'Episode 77', 'url': 'link'},
        {'titleeps': 'Episode 78', 'url': 'link'},
        {'titleeps': 'Episode 79', 'url': 'link'},
        {'titleeps': 'Episode 80', 'url': 'link'},
        {'titleeps': 'Episode 81', 'url': 'link'},
        {'titleeps': 'Episode 82', 'url': 'link'},
        {'titleeps': 'Episode 83', 'url': 'link'},
        {'titleeps': 'Episode 84', 'url': 'link'},
        {'titleeps': 'Episode 85', 'url': 'link'},
        {'titleeps': 'Episode 86', 'url': 'link'},
        {'titleeps': 'Episode 87', 'url': 'link'},
        {'titleeps': 'Episode 88', 'url': 'link'},
        {'titleeps': 'Episode 89', 'url': 'link'},
        {'titleeps': 'Episode 90', 'url': 'link'},
        {'titleeps': 'Episode 91', 'url': 'link'},
        {'titleeps': 'Episode 92', 'url': 'link'},
        {'titleeps': 'Episode 93', 'url': 'link'},
        {'titleeps': 'Episode 94', 'url': 'link'},
        {'titleeps': 'Episode 95', 'url': 'link'},
        {'titleeps': 'Episode 96', 'url': 'link'},
        {'titleeps': 'Episode 97', 'url': 'link'},
        {'titleeps': 'Episode 98', 'url': 'link'},
        {'titleeps': 'Episode 99', 'url': 'link'},
        {'titleeps': 'Episode 100', 'url': 'link'},
        {'titleeps': 'Episode 101', 'url': 'link'},
        {'titleeps': 'Episode 102', 'url': 'link'},
        {'titleeps': 'Episode 103', 'url': 'link'},
        {'titleeps': 'Episode 104', 'url': 'link'},
        {'titleeps': 'Episode 105', 'url': 'link'},
        {'titleeps': 'Episode 106', 'url': 'link'},
        {'titleeps': 'Episode 107', 'url': 'link'},
        {'titleeps': 'Episode 108', 'url': 'link'},
        {'titleeps': 'Episode 109', 'url': 'link'},
        {'titleeps': 'Episode 110', 'url': 'link'},
        {'titleeps': 'Episode 111', 'url': 'link'},
        {'titleeps': 'Episode 112', 'url': 'link'},
        {'titleeps': 'Episode 113', 'url': 'link'},
        {'titleeps': 'Episode 114', 'url': 'link'},
        {'titleeps': 'Episode 115', 'url': 'link'},
        {'titleeps': 'Episode 116', 'url': 'link'},
        {'titleeps': 'Episode 117', 'url': 'link'},
        {'titleeps': 'Episode 118', 'url': 'link'},
        {'titleeps': 'Episode 119', 'url': 'link'},
        {'titleeps': 'Episode 120', 'url': 'link'},
        {'titleeps': 'Episode 121', 'url': 'link'},
        {'titleeps': 'Episode 122', 'url': 'link'},
        {'titleeps': 'Episode 123', 'url': 'link'},
        {'titleeps': 'Episode 124', 'url': 'link'},
        {'titleeps': 'Episode 125', 'url': 'link'},
        {'titleeps': 'Episode 126', 'url': 'link'},
        {'titleeps': 'Episode 127', 'url': 'link'},
        {'titleeps': 'Episode 128', 'url': 'link'},
        {'titleeps': 'Episode 129', 'url': 'link'},
        {'titleeps': 'Episode 130', 'url': 'link'},
      ],
      'jenis': 'Donghua',
      'musim': '2021',
      'description': 'Donghua “Perfect World” diadaptasi dari novel dengan judul yang sama. Dia dilahirkan untuk mengolah Tao, dan untuk malapetaka, dia berubah menjadi hujan ribuan darah, turun selama berabad-abad, dan mengalami waktu dan ruang yang tak terhitung jumlahnya, pemurnian bertahun-tahun, dia berbalik selamanya. Lihat bagaimana pahlawan Shi Hao yang sangat brilian sepanjang hidupnya, menciptakan legenda tanpa akhir.'
    },
    {'title': 'Battle Through the Heavens Season 5',
      'mandarin': '斗破苍穹年番, Doupo Cangqiong: Nian Fan Fights Break Sphere 5th Season',
      'rating': 9.20,
      'image': 'assets/DONGHUA/BTTH.jpg',
      'genre': ['Action', 'Adventure', 'Fantasy'],
      'status': 'Ongoing',
      'studio': 'Motion Magic',
      'releaseDate': '21 December 2022',
      'update': '1 December 2024',
      'duration': '24 min.',
      'totaleps': '13 Episode',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
        {'titleeps': 'Episode 11', 'url': 'link'},
        {'titleeps': 'Episode 12', 'url': 'link'},
        {'titleeps': 'Episode 13', 'url': 'link'},
        {'titleeps': 'Episode 14', 'url': 'link'},
        {'titleeps': 'Episode 15', 'url': 'link'},
        {'titleeps': 'Episode 16', 'url': 'link'},
        {'titleeps': 'Episode 17', 'url': 'link'},
        {'titleeps': 'Episode 18', 'url': 'link'},
        {'titleeps': 'Episode 19', 'url': 'link'},
        {'titleeps': 'Episode 20', 'url': 'link'},
        {'titleeps': 'Episode 21', 'url': 'link'},
        {'titleeps': 'Episode 22', 'url': 'link'},
        {'titleeps': 'Episode 23', 'url': 'link'},
        {'titleeps': 'Episode 24', 'url': 'link'},
        {'titleeps': 'Episode 25', 'url': 'link'},
        {'titleeps': 'Episode 26', 'url': 'link'},
        {'titleeps': 'Episode 27', 'url': 'link'},
        {'titleeps': 'Episode 28', 'url': 'link'},
        {'titleeps': 'Episode 29', 'url': 'link'},
        {'titleeps': 'Episode 30', 'url': 'link'},
        {'titleeps': 'Episode 31', 'url': 'link'},
        {'titleeps': 'Episode 32', 'url': 'link'},
        {'titleeps': 'Episode 33', 'url': 'link'},
        {'titleeps': 'Episode 34', 'url': 'link'},
        {'titleeps': 'Episode 35', 'url': 'link'},
        {'titleeps': 'Episode 36', 'url': 'link'},
        {'titleeps': 'Episode 37', 'url': 'link'},
        {'titleeps': 'Episode 38', 'url': 'link'},
        {'titleeps': 'Episode 39', 'url': 'link'},
        {'titleeps': 'Episode 40', 'url': 'link'},
        {'titleeps': 'Episode 41', 'url': 'link'},
        {'titleeps': 'Episode 42', 'url': 'link'},
        {'titleeps': 'Episode 44', 'url': 'link'},
        {'titleeps': 'Episode 45', 'url': 'link'},
        {'titleeps': 'Episode 46', 'url': 'link'},
        {'titleeps': 'Episode 47', 'url': 'link'},
        {'titleeps': 'Episode 48', 'url': 'link'},
        {'titleeps': 'Episode 49', 'url': 'link'},
        {'titleeps': 'Episode 50', 'url': 'link'},
        {'titleeps': 'Episode 51', 'url': 'link'},
        {'titleeps': 'Episode 52', 'url': 'link'},
      ],
      'jenis': 'Donghua',
      'musim': 'Summer 2022',
      'description': 'Musim kelima Doupo Cangqiong. Setelah tiga tahun tidak bertemu, Xiao Yan akhirnya bertemu Xun’er di Akademi Jia Nan . Setelah itu, mereka menjadi lebih dekat dan mendirikan Gerbang Batu (Gerbang Pan). Untuk terus meningkatkan kekuatannya dan membalaskan dendamnnya pada Sekte Misty Cloud, dia mengambil resiko dengan masuk lebih dalam ke Pagoda Pemurnian Qi untuk berlatih dan melahap Api Fallen Heart Flame.'
    },
    {'title': 'Throne of Seal Season 2',
      'rating': 7.72,
      'mandarin': 'Shen Yin Wangzuo 2nd Season',
      'image': 'assets/DONGHUA/throne_of_seal.jpg',
      'genre': ['Action', 'Fantasy', 'Fantasy'],
      'status': 'Ongoing',
      'studio': 'Shenman Entertainment',
      'releaseDate': '29 April 2022',
      'update': '5 December 2024',
      'duration': '20 min.',
      'totaleps': '157 Episodes',
      'episodes': [ 
        {'titleeps': 'Episode 1', 'url': 'link'},
        {'titleeps': 'Episode 2', 'url': 'link'},
        {'titleeps': 'Episode 3', 'url': 'link'},
        {'titleeps': 'Episode 4', 'url': 'link'},
        {'titleeps': 'Episode 5', 'url': 'link'},
        {'titleeps': 'Episode 6', 'url': 'link'},
        {'titleeps': 'Episode 7', 'url': 'link'},
        {'titleeps': 'Episode 8', 'url': 'link'},
        {'titleeps': 'Episode 9', 'url': 'link'},
        {'titleeps': 'Episode 10', 'url': 'link'},
        {'titleeps': 'Episode 11', 'url': 'link'},
        {'titleeps': 'Episode 12', 'url': 'link'},
        {'titleeps': 'Episode 13', 'url': 'link'},
        {'titleeps': 'Episode 14', 'url': 'link'},
        {'titleeps': 'Episode 15', 'url': 'link'},
        {'titleeps': 'Episode 16', 'url': 'link'},
        {'titleeps': 'Episode 17', 'url': 'link'},
        {'titleeps': 'Episode 18', 'url': 'link'},
        {'titleeps': 'Episode 19', 'url': 'link'},
        {'titleeps': 'Episode 20', 'url': 'link'},
        {'titleeps': 'Episode 21', 'url': 'link'},
        {'titleeps': 'Episode 22', 'url': 'link'},
        {'titleeps': 'Episode 23', 'url': 'link'},
        {'titleeps': 'Episode 24', 'url': 'link'},
        {'titleeps': 'Episode 25', 'url': 'link'},
        {'titleeps': 'Episode 26', 'url': 'link'},
        {'titleeps': 'Episode 27', 'url': 'link'},
        {'titleeps': 'Episode 28', 'url': 'link'},
        {'titleeps': 'Episode 29', 'url': 'link'},
        {'titleeps': 'Episode 30', 'url': 'link'},
        {'titleeps': 'Episode 31', 'url': 'link'},
        {'titleeps': 'Episode 32', 'url': 'link'},
        {'titleeps': 'Episode 33', 'url': 'link'},
        {'titleeps': 'Episode 34', 'url': 'link'},
        {'titleeps': 'Episode 35', 'url': 'link'},
        {'titleeps': 'Episode 36', 'url': 'link'},
        {'titleeps': 'Episode 37', 'url': 'link'},
        {'titleeps': 'Episode 38', 'url': 'link'},
        {'titleeps': 'Episode 39', 'url': 'link'},
        {'titleeps': 'Episode 40', 'url': 'link'},
        {'titleeps': 'Episode 41', 'url': 'link'},
        {'titleeps': 'Episode 42', 'url': 'link'},
        {'titleeps': 'Episode 44', 'url': 'link'},
        {'titleeps': 'Episode 45', 'url': 'link'},
        {'titleeps': 'Episode 46', 'url': 'link'},
        {'titleeps': 'Episode 47', 'url': 'link'},
        {'titleeps': 'Episode 48', 'url': 'link'},
        {'titleeps': 'Episode 49', 'url': 'link'},
        {'titleeps': 'Episode 50', 'url': 'link'},
        {'titleeps': 'Episode 51', 'url': 'link'},
        {'titleeps': 'Episode 52', 'url': 'link'},
        {'titleeps': 'Episode 53', 'url': 'link'},
        {'titleeps': 'Episode 54', 'url': 'link'},
        {'titleeps': 'Episode 55', 'url': 'link'},
        {'titleeps': 'Episode 56', 'url': 'link'},
        {'titleeps': 'Episode 57', 'url': 'link'},
        {'titleeps': 'Episode 58', 'url': 'link'},
        {'titleeps': 'Episode 59', 'url': 'link'},
        {'titleeps': 'Episode 60', 'url': 'link'},
        {'titleeps': 'Episode 61', 'url': 'link'},
        {'titleeps': 'Episode 62', 'url': 'link'},
        {'titleeps': 'Episode 63', 'url': 'link'},
        {'titleeps': 'Episode 64', 'url': 'link'},
        {'titleeps': 'Episode 65', 'url': 'link'},
        {'titleeps': 'Episode 66', 'url': 'link'},
        {'titleeps': 'Episode 67', 'url': 'link'},
        {'titleeps': 'Episode 68', 'url': 'link'},
        {'titleeps': 'Episode 69', 'url': 'link'},
        {'titleeps': 'Episode 70', 'url': 'link'},
        {'titleeps': 'Episode 71', 'url': 'link'},
        {'titleeps': 'Episode 72', 'url': 'link'},
        {'titleeps': 'Episode 73', 'url': 'link'},
        {'titleeps': 'Episode 74', 'url': 'link'},
        {'titleeps': 'Episode 75', 'url': 'link'},
        {'titleeps': 'Episode 76', 'url': 'link'},
        {'titleeps': 'Episode 77', 'url': 'link'},
        {'titleeps': 'Episode 78', 'url': 'link'},
        {'titleeps': 'Episode 79', 'url': 'link'},
        {'titleeps': 'Episode 80', 'url': 'link'},
        {'titleeps': 'Episode 81', 'url': 'link'},
        {'titleeps': 'Episode 82', 'url': 'link'},
        {'titleeps': 'Episode 83', 'url': 'link'},
        {'titleeps': 'Episode 84', 'url': 'link'},
        {'titleeps': 'Episode 85', 'url': 'link'},
        {'titleeps': 'Episode 86', 'url': 'link'},
        {'titleeps': 'Episode 87', 'url': 'link'},
        {'titleeps': 'Episode 88', 'url': 'link'},
        {'titleeps': 'Episode 89', 'url': 'link'},
        {'titleeps': 'Episode 90', 'url': 'link'},
        {'titleeps': 'Episode 91', 'url': 'link'},
        {'titleeps': 'Episode 92', 'url': 'link'},
        {'titleeps': 'Episode 93', 'url': 'link'},
        {'titleeps': 'Episode 94', 'url': 'link'},
        {'titleeps': 'Episode 95', 'url': 'link'},
        {'titleeps': 'Episode 96', 'url': 'link'},
        {'titleeps': 'Episode 97', 'url': 'link'},
        {'titleeps': 'Episode 98', 'url': 'link'},
        {'titleeps': 'Episode 99', 'url': 'link'},
        {'titleeps': 'Episode 100', 'url': 'link'},
        {'titleeps': 'Episode 101', 'url': 'link'},
        {'titleeps': 'Episode 102', 'url': 'link'},
        {'titleeps': 'Episode 103', 'url': 'link'},
        {'titleeps': 'Episode 104', 'url': 'link'},
        {'titleeps': 'Episode 105', 'url': 'link'},
        {'titleeps': 'Episode 106', 'url': 'link'},
        {'titleeps': 'Episode 107', 'url': 'link'},
        {'titleeps': 'Episode 108', 'url': 'link'},
        {'titleeps': 'Episode 109', 'url': 'link'},
        {'titleeps': 'Episode 110', 'url': 'link'},
        {'titleeps': 'Episode 111', 'url': 'link'},
        {'titleeps': 'Episode 112', 'url': 'link'},
        {'titleeps': 'Episode 113', 'url': 'link'},
        {'titleeps': 'Episode 114', 'url': 'link'},
        {'titleeps': 'Episode 115', 'url': 'link'},
        {'titleeps': 'Episode 116', 'url': 'link'},
        {'titleeps': 'Episode 117', 'url': 'link'},
        {'titleeps': 'Episode 118', 'url': 'link'},
        {'titleeps': 'Episode 119', 'url': 'link'},
        {'titleeps': 'Episode 120', 'url': 'link'},
        {'titleeps': 'Episode 121', 'url': 'link'},
        {'titleeps': 'Episode 122', 'url': 'link'},
        {'titleeps': 'Episode 123', 'url': 'link'},
        {'titleeps': 'Episode 124', 'url': 'link'},
        {'titleeps': 'Episode 125', 'url': 'link'},
        {'titleeps': 'Episode 126', 'url': 'link'},
        {'titleeps': 'Episode 127', 'url': 'link'},
        {'titleeps': 'Episode 128', 'url': 'link'},
        {'titleeps': 'Episode 129', 'url': 'link'},
        {'titleeps': 'Episode 130', 'url': 'link'},
        {'titleeps': 'Episode 131', 'url': 'link'},
        {'titleeps': 'Episode 132', 'url': 'link'},
        {'titleeps': 'Episode 133', 'url': 'link'},
        {'titleeps': 'Episode 134', 'url': 'link'},
        {'titleeps': 'Episode 135', 'url': 'link'},
        {'titleeps': 'Episode 136', 'url': 'link'},
        {'titleeps': 'Episode 137', 'url': 'link'},
        {'titleeps': 'Episode 138', 'url': 'link'},
        {'titleeps': 'Episode 139', 'url': 'link'},
        {'titleeps': 'Episode 140', 'url': 'link'},
        {'titleeps': 'Episode 141', 'url': 'link'},
        {'titleeps': 'Episode 142', 'url': 'link'},
        {'titleeps': 'Episode 143', 'url': 'link'},
        {'titleeps': 'Episode 144', 'url': 'link'},
        {'titleeps': 'Episode 145', 'url': 'link'},
        {'titleeps': 'Episode 146', 'url': 'link'},
        {'titleeps': 'Episode 147', 'url': 'link'},
        {'titleeps': 'Episode 148', 'url': 'link'},
        {'titleeps': 'Episode 149', 'url': 'link'},
        {'titleeps': 'Episode 150', 'url': 'link'},
        {'titleeps': 'Episode 151', 'url': 'link'},
        {'titleeps': 'Episode 152', 'url': 'link'},
        {'titleeps': 'Episode 153', 'url': 'link'},
        {'titleeps': 'Episode 154', 'url': 'link'},
        {'titleeps': 'Episode 155', 'url': 'link'},
        {'titleeps': 'Episode 156', 'url': 'link'},
        {'titleeps': 'Episode 157', 'url': 'link'},
      ],
      'jenis': 'Movie',
      'musim': '2016',
      'description': 'Dalam petualangan pertumbuhan selangkah demi selangkah, petualangan, trik, dan cinta serta persahabatan yang ditakdirkan terus terungkap.Dia, Long Haochen menganut semangat ksatria dan memenangkan pengakuan orang lain melalui kepribadian dan kerja kerasnya. Dia pertama kali membentuk “Kelompok Pemburu Iblis No. 1” dengan remaja berbakat lainnya di Enam Kuil untuk melawan iblis, berjuang untuk kelangsungan hidup dan martabat manusia.'
    },
    ];


    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: const Color.fromARGB(201, 34, 167, 255),
        title: Text(
          'Top Donghua',
          style: GoogleFonts.eduNswActFoundation(
            textStyle: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.bold,
              fontSize: 30,
            ),
          ),
        ),
        flexibleSpace: Container(
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              colors: [
                Color.fromARGB(255, 250, 100, 95),
                Color.fromARGB(255, 250, 100, 95),
                Color.fromARGB(255, 250, 100, 95),
              ],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
          ),
        ),
      ),
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [
              Color(0xFF1E1E30),
              Color(0xFF1E1E30),
              Color(0xFF000000),
            ],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [  // Pemanggilan search bar
            const SizedBox(height: 10),  // Jarak antara search bar dan GridView
            Expanded(
              child: GridView.builder(
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 3,
                  crossAxisSpacing: 8.0,
                  mainAxisSpacing: 8.0,
                  childAspectRatio: 0.7,
                ),
                itemCount: donghuaList1.length,
                itemBuilder: (context, index) {
                  final donghua = donghuaList1[index];
                  return _buildAnimeCard(context, donghua);
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
  Widget _buildAnimeCard(BuildContext context, Map<String, dynamic> donghua) {
    return GestureDetector(
      onTap: () {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => DonghuaDetail(
              donghua: {
                'title': donghua['title'],
                'mandarin': donghua['mandarin'],
                'image': donghua['image'],
                'genre': donghua['genre'],
                'rating': donghua['rating'],
                'status': donghua['status'],
                'studio': donghua['studio'],
                'releaseDate': donghua['releaseDate'],
                'update': donghua['update'],
                'duration': donghua['duration'],
                'totaleps': donghua['totaleps'],
                'episodes': {donghua['titleeps'], donghua['url']},
                'jenis': donghua['jenis'],
                'musim': donghua['musim'],
                'description': donghua['description'],
              },
            ),
          ),
        );
      },
      child: Container(
        width: 160,
        margin: const EdgeInsets.symmetric(horizontal: 5.0),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(8.0),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.2),
              blurRadius: 6.0,
              offset: const Offset(0, 3),
            ),
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(8.0),
          child: Stack(
            children: [
              // Gambar Donghua
              Image.asset(
                donghua['image'],
                fit: BoxFit.cover,
                width: double.infinity,
                height: double.infinity,
              ),
              // Rating di posisi topleft
              Positioned(
                top: 8,
                left: 8,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 6.0, vertical: 4.0),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.7),
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: Row(
                    children: [
                      const Icon(
                        Icons.star,
                        color: Colors.yellow,
                        size: 14.0,
                      ),
                      const SizedBox(width: 4),
                      Text(
                        donghua['rating'].toString(), // Rating dari data
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 12.0,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              // Judul di posisi bottom center
              Positioned(
                bottom: 0,
                left: 0,
                right: 0,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 6.0, vertical: 4.0),
                  decoration: BoxDecoration(
                    color: Colors.black.withOpacity(0.6),
                  ),
                  child: Text(
                    donghua['title'],
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 14.0,
                      fontWeight: FontWeight.bold,
                    ),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

